server {
  listen 80;
  index index.php index.html index.htm;
  
  root /var/www/html/tkj-inventory/public;

  location / {
    try_files $uri $uri/ /index.php?$query_string;
  }

  location ~ \.php$ {
    fastcgi_pass tkj_inventory:9000; # Same as docker compose on ./docker-compose.yml
    fastcgi_index index.php;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param PATH_INFO $fastcgi_path_info;
  }

  # Following option on README.md
  # See detail on https://github.com/tkjskanesga/tkj-inventory#1-server-configuration
  client_max_body_size 25M;

  # Strict
  location ~ ^/(config|temp|cron|tkj_inventory.sql) {
    deny all;
    return 404;
  }
}